apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: free-rules
spec:
  selector:
    matchLabels:
      app: auth
  action: ALLOW
  rules:
  - to: 
    - operation:
        paths: ["/api/user/*"]