{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.ingress.host }}
spec:
  hosts:
  {{- if eq .Values.ingress.domain "minikube.local" }}
  - "*"
  {{- else }}
  - "{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}"
  {{- end }}
  gateways:
  - {{ .Values.ingress.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.ingress.prefix }}
    route:
    - destination:
        port:
          number: {{ .Values.streamsServer.network.containerPort }}
        host: "{{ .Release.Name }}-service.{{ .Release.Namespace }}.svc.cluster.local"
{{- end -}}

