apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Values.namespace }}
data: 
  {{- range $key, $val := .Values.env.configMap.data }}
  {{$key}}: {{  $val }}
  {{- end }}
