apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range $key, $val := .Values.configmap.data }}
  {{$key}}: {{ $val | quote}}
  {{- end }}
  DJANGO_ALLOWED_HOSTS: www.example.com localhost 127.0.0.1 169.254.123.249 host.docker.internal 172.17.0.1 169.254.227.142 ui.default.svc.cluster.local
  DJANGO_CORS_ORIGIN_WHITELIST: http://google.com http://localhost:3000 http://127.0.0.1:3000 http://host.minikube.internal:3000 http://host.docker.internal:3000 http://172.17.0.1:3000 http://ui.default.svc.cluster.local