apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.env.Secret.data }}
  {{$key}}: {{ $val }}
  {{- end }}

