apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secrets
type: Opaque
data:  
  {{- range $key, $val := .Values.secrets.data }}
  {{$key}}: {{ $val }}
  {{- end }}
  JWT_SIGNING_KEY: {{ .Values.jwt_keys.JWT_SIGNING_KEY | toYaml | indent 1}}
  JWT_VERIFYING_KEY: {{ .Values.jwt_keys.JWT_VERIFYING_KEY | toYaml | indent 1 }}
